name: ToDoListAPI Performance Test
run-name: ToDoListAPI Performance Test

on: workflow_dispatch

jobs:
  Perftest:
    runs-on: ubuntu-latest
        
    steps:
      - name: JMeter Test
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: ./Tests/PerformanceTests/ToDoListAPI-PerformanceTest.jmx
          args: ""

      - name: Upload Results
        uses: actions/upload-artifact@v3.1.21
        with:
          name: jmeter-results
          path: result.jtl